### PR TITLE
Improve reading functionality

### LINKED ISSUE #29: Upload PDST file with acceleration data
The current 'pdst_raw_to_tidy.R' code uses datasets with two datablocks: temperature and depth. I know want to include files with an extra datablock being acceleration. Hence, the script needs to be adapted to also store these data in the daylog and sensorlog files. Example data on request.

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR:
1. Allows importing acceleration data (fixes #29)
2. Makes import code generic and sensor independent. No matter how many data blocks are stored and which kind of sensor data it contains (temperature, pressure, acceleration, ...).
3. Allows reading data with heterogeneous datetime formats. At the moment, only `d/m/y H:M` and `d/m/y H:M:S` are used. Notice that having files with heterogeneous datetime formats is bad practice.
4. In case the same datetime value is repeated in multiple rows (it happens in acceleration file `"./data/raw/A15881_04-09-2020_cleaned.csv"` when datetime is formatted as `d/m/y H:M`), makes these rows unique by adding second values. When there are 30 rows per datetime, the datetime values are separated by 2 seconds, if 60 rows are present, they are separated by 1 second
5. adds a cleaning function `clean_file()`, to remove a specific pattern over all lines of a data file. It has been noticed that some files (`A15881_04-09-2020.csv`) have a suspect repeated pattern on several rows, e.g. `",,,,,,,"`.
6. Improves the reading files loop in `pdst_raw_to_tidy.R` to allow reading the cleaned file if present.

### CODE REVIEW

**Comment by PieterjanVerhelst** [comment]
@damianooldoni I quickly ran a test (on the train with limited internet access and laptop battery is about to run dead, so quick response). I got an error:

`Firmware version: 3,,,,,,.80,,,,,,
Error in pdst_get_data(filename) : object 'p' not found`

**Comment by damianooldoni** [comment]
Indeed, a problem in the code to select the data files to read. Sorry. Solved in c76c635. Please, pull and try again. We have to use the cleaned versions of the files, if present. So, `data_files` should contain `A15881_04-09-2020_cleaned.csv` and not `A15881_04-09-2020.csv`. On my laptop:

```r
> data_files
[1] "./data/raw/A03486_25-03-2009.csv"        
[2] "./data/raw/A06869_13-07-2012.CSV"        
[3] "./data/raw/A15881_04-09-2020_cleaned.csv"
[4] "./data/raw/A17480_27-01-2020.csv"  
```

To clean `A15881_04-09-2020.csv`, run `clean_file("A15881_04-09-2020.csv")`: it will generated a new file in `./data/raw/` with suffix `_cleaned` and with 5 or more consecutive commas removed.

**Comment by PieterjanVerhelst** [comment]
@damianooldoni perfect, now it works 👏 ! Would it however not be possible to implement the cleaning automatically in the `pdst_raw_to_tidy.R` script? As in: if data needs to be cleaned --> `clean(df)`, else(use raw data)

**Comment by damianooldoni** [comment]
Done. Please pull and check again. I have modified a little the `clean_file()` function so that it generates a cleaned version only if needed. Also, you can now specify a different suffix than `"_cleaned"`, which is still used as default value.

**Comment by PieterjanVerhelst** [comment]
Perfect, it works 👍 ! I will test on a few more datasets and keep you posted on the pull request 👌 .

**Pull request merged**
